os: linux
language: python

script: skip

deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: dSkAJtH2UWY+525rwmDOJOCECnbDuKFJcDV4l+06VvP1guPUjdyNFs5J+f1jQ2NGg/QpFkmnEJIVzT70UBuc8jasTZhyHT+cqOiK0P0Wfn0ZqxWBIekFWiPkpQi54GSTTMdiZl7JVmZV10DRo51CgM98c6Ejv4/Nuvm1U5SWNS5lSjnxUJm4lVjZq8flvzZ+z9VUNXCwvu79nEoP/yE/2P+8+ZpBAQQ7+cep5FGa49tWgu92mPlnktRVWK3riZL54ZuMNNyj+z+mCbcpoZ4ns//BEnz05Lx2LPCiXpV+9Q1JHGGC1SDQA8l16XP0SiwCMjWqkjRDVJpahUvZ/vRrKaGglDSpZN/F1uDzBMIF56uLNTzORO5wmKtZ8ecEN4F5fCyXQdxm1ljCQQq9wJHLYhLyvbAQ9ES7laAu0bTp517MgciXu7BZXyu5U2+PeeNipl3PqyCcb55bo8uaG2xGMzC3yjsROvb6OXrpJGATwkMLnsZaBvxXJEOW1VSIJzHvbJ72o2XuFBlngbpmO+VEIGyzFQY6w1aPXVrEsLoAMnOmE+aSDk6ofMMZvXCf8b3JBI5r2PmfXZG/zPFaUb88tUCvch2Eja3G73Feh1Oib3zwGdIDU68463QVBZY6lWeVrUiIFfO31bIw3Otskh5zm/GLSthqWK/xW+I9jGbF0E4=
  on:
    tags: true
  skip_cleanup: 'true'
