os: linux
language: python
script: skip
deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: wPrQERSLIwJijD0XfwbMGAH2k3v4txTYslAc5Ker5hhHiiC2YL1i2kcBm/7hTAn5eTEproze1GUpNADo7HEkXX6MS603xnbOG59v3/QSk7zMej+L/zgDnYxAFQJGZe/4tJmiDgBJi6n98bfhHDYAK5iTtC1okgpBgf835T3a7x8de5zc12KjsHaxz068h8pW1pUzqCeh4VEg4xcWyqEcGI5g3IcdP600EB0Qmgjc/M+65drwDLeufEPrzuccDVLJA7fotZiB2o3gUdjCO7RAnrMzr+iV6V6pFFDA3FiV9xVUoper+OBKLn4SF5TQ9GQsgX5Y5ByAaN8W4a99c+NDCvspcxPCoG8wJeAtXpz45yOB1auD5N94uQz1Tg7E52ohV3BSKOgZIlljeZ9VZF5+P/QF77sYGP7x64z1pPRjV59JfyuRA30/HmgkePdL+yGynHyW5J6XJNZ+LimQ5k80s/0eOdQeamzA9vtPV7ggjjdi+LQeLcWx6xvdWCF0yozRUwlro7kqZeCpxXe08IKL53hOVwlJsw32U7t0A9DwK0AW0sF7TxhOMz+fPRbY50VRP5jHal6xN91kGVV+hnMPm3FPhbkfUKCC6jBCF9nFiwBszJ6rJnxWshQsj7ifU0bWkg+yY8vdmj1KFpP+642VnKJ77JwBuIHvtF4JAB4p8AU=
  on:
    tags: true
  skip_cleanup: 'true'
